(ns p-0002)

;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(defn fib 
  ([]
   (fib 0M 1M))
  ([a b]
   (let [c (+ a b)]
     (lazy-seq (cons c (fib b c))))))

(defn big-even? [n]
  (zero? (mod n 2)))

(->> (fib)
     (sequence (comp (take-while #(< % 4000000M))
                     (filter big-even?)))
     (reduce +))
